# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sn50EDl2TZtcQ1sRf99IqaHdIV3Ful1W
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
#import seaborn as sns
#sns.set()
data = pd.read_csv('daa.csv')
data
#data.head()
#data.describe()

# Dependent Variable 
y = data['price']
# Independent Variable
x1 = data['size']
plt.scatter(x1, y)
plt.xlabel('size')
plt.ylabel('price')
plt.show()

# Regression Equation 
# yhat = b0 + b1*x1

x = sm.add_constant(x1)
results = sm.OLS(y,x).fit()
results.summary()

plt.scatter(x1, y)
yhat = 223.1787*x1 + 1.019e+05
fig = plt.plot(x1, yhat) 
plt.xlabel('size')
plt.ylabel('price')
plt.show()

new_data = pd.DataFrame({'const':1, 'size': [1700, 1650]})
new_data = new_data[['const', 'size']]

predictions = results.predict(new_data)

pre_df = pd.DataFrame({'Predictions': predictions})
new_data = new_data.join(pre_df)

new_data

